### ISSUE TITLE
Need help, I'm unable to build libfvde on my Mac OS 10.14 installation

### ISSUE THREAD

**Issue by therightprofile** [libyal/libfvde#48] opened 2020-04-25 11:29 UTC
I am unable to build any of the source distribution packages (20190104, 20191221) as well as with git clone on macos 10.14.

It seems to be related to the libcaes library. 

Here's the error I get on make:

```
libcaes_context.c:365:6: error: use of undeclared identifier 'libcaes_tables_initialized'; did you mean
      'libcaes_context_initialize'?
        if( libcaes_tables_initialized == 0 )

```

```
libcaes_context.c:379:3: error: use of undeclared identifier 'libcaes_tables_initialized'
                libcaes_tables_initialized = 1;
```

**Comment by joachimmetz** [comment] 2020-04-25 13:30
Can you attach your config.log. The CI builds seems fine, so I expect this to be something specific to your build environment.

**Comment by joachimmetz** [comment] 2020-04-26 09:04
I just built 20191221 on MacOS 10.14 on a clean installation with XCode without any issues. As I indicated please provide your config.log I suspect this is something specific to your installation.

**Comment by therightprofile** [comment] 2020-04-26 17:04
Here's my config.log

[config.log](https://github.com/libyal/libfvde/files/4535995/config.log)

Thanks!

**Comment by joachimmetz** [comment] 2020-05-11 08:24
Finally had some time for a brief look:
```
ax_libcrypto_pc_libs_private=''
ax_libcrypto_spec_build_requires=''
ax_libcrypto_spec_requires=''
...
openssl_CFLAGS=''
openssl_LIBS=''
```

```
Building:
   libcerror support:                         local
   libcthreads support:                       local
   libcdata support:                          local
   libclocale support:                        local
   libcnotify support:                        local
   libcsplit support:                         local
   libuna support:                            local
   libcfile support:                          local
   libcpath support:                          local
   libbfio support:                           local
   libfcache support:                         local
   libfdata support:                          local
   libfguid support:                          local
   libfplist support:                         local
   libfvalue support:                         local
   DEFLATE compression support:               local
   libhmac support:                           local
   SHA256 support:                            local
   libcaes support:                           local
   AES-ECB support:                           local
   AES-XTS support:                           local
   FUSE support:                              libosxfuse

Features:
   Multi-threading support:                   pthread
   Wide character type support:               no
   fvdetools are build as static executables: no
   Python (pyfvde) support:                   no
   Verbose output:                            no
   Debug output:                              no
```

This corresponds roughly with my test.

libcaes_tables_initialized not being defined here https://github.com/libyal/libcaes/blob/20190102/libcaes/libcaes_context.c#L365 could be because LIBCAES_HAVE_AES_SUPPORT is defined (https://github.com/libyal/libcaes/blob/20190102/libcaes/libcaes_definitions.h.in#L54). I'll have a look what could trigger this. I'd also noticed that you have a lot of PATHs

**Comment by joachimmetz** [comment] 2020-05-11 08:29
I only see `HAVE_OPENSSL_EVP_H` defined in config.log

```
HAVE_OPENSSL_EVP_H=''
```

**Comment by joachimmetz** [comment] 2020-05-11 08:32
Though I see your config.log is from 20190104.

**Comment by joachimmetz** [comment] 2020-05-11 08:42
I see you are using `./configure --disable-shared-libs` maybe that is causing the issue.

**Comment by joachimmetz** [comment] 2021-09-26 04:36
libcaes has been updated in the mean time, try again with the latest. Closing this issue for now, since it was not reproducible.

**Closed by joachimmetz** 2021-09-26 04:36 UTC
Labels: question
